const INVALID_USER_ID = 400;
const INVALID_CARD_ID = 400;
const INVALID_PARAMETERS = 400;
const INVALID_ROUTE = 404;
const USER_NOT_FOUND = 404;
const CARD_NOT_FOUND = 404;
const DB_ERROR = 500;

module.exports = {
  INVALID_USER_ID,
  INVALID_CARD_ID,
  INVALID_PARAMETERS,
  INVALID_ROUTE,
  USER_NOT_FOUND,
  CARD_NOT_FOUND,
  DB_ERROR,
};
